// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqcdpbvnkhxdhsvyoens.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxY2RwYnZua2h4ZGhzdnlvZW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzk3MDYsImV4cCI6MjA2Mjc1NTcwNn0.2rHdCXrez2QfoORU03UA--i-UDFNSJ9X7VLJDEsaCfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);